Babel to the server side to use ES6 features Completed
pesto-students/batch-12-WeConnect pull request #18
Opened 2020-02-13 11:04 UTC by nitishmittal1990

Closes #4

2020-02-13 11:17 UTC, fenilgandhi approved these changes

2020-02-13 14:46 UTC, fenilgandhi requested changes

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +<<<<<<< HEAD
Hey @nitishmittal1990 , need to resolve this.

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +<<<<<<< HEAD
and this.

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +=======
and this too.

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +<<<<<<< HEAD
.

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +<<<<<<< HEAD
..

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +=======
..

2020-02-13 14:46 UTC, fenilgandhi commented on yarn.lock
> +<<<<<<< HEAD
...

2020-02-13 15:45 UTC, fenilgandhi approved these changes

2020-02-14 03:53 UTC, rishabh1403 commented
Use better PR names. 
also some files are missing new line at the end. Please resolve those

2020-02-14 07:27 UTC, nitishmittal1990 commented
> Use better PR names.
> also some files are missing new line at the end. Please resolve those

Updated above 2 points

2020-02-14 10:07 UTC, nimish-gupta approved these changes
LGTM.

2020-02-14 11:33 UTC, merged